#!/bin/bash

path=~/.nanorc
if [[ -f ${path} ]]
then
	# Mr Awk trying to make it hard lol
	echo "" | awk 'BEGIN{print "Yes, Its exist"}'
	#echo "File Exist"
else
	cp /etc/nanorc ~/.nanorc
	#echo -n "include " >> .nanorc
	echo include "/usr/local/Cellar/nano/*/share/nano/*.nanorc" >> .nanorc
fi
